platform :osx, '10.10'

 target 'TRTCDemo' do
# pod 'TXLiteAVSDK_TRTC_Mac', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_TRTC_Mac.podspec'
 pod 'TXLiteAVSDK_TRTC_Mac'
 end
