declare const styles: {
  readonly "el-button-group": string;
  readonly "el-button": string;
  readonly "is-active": string;
  readonly "is-disabled": string;
  readonly "is-plain": string;
  readonly "el-button--text": string;
  readonly "is-loading": string;
  readonly "is-round": string;
  readonly "is-circle": string;
  readonly "el-button--primary": string;
  readonly "el-button--success": string;
  readonly "el-button--warning": string;
  readonly "el-button--danger": string;
  readonly "el-button--info": string;
  readonly "el-button--medium": string;
  readonly "el-button--mini": string;
  readonly "el-button--small": string;
  readonly "el-dropdown": string;
  readonly "el-calendar": string;
  readonly "el-calendar__header": string;
  readonly "el-calendar__title": string;
  readonly "el-calendar__body": string;
  readonly "el-calendar-table": string;
  readonly "is-range": string;
  readonly "next": string;
  readonly "prev": string;
  readonly "is-selected": string;
  readonly "is-today": string;
  readonly "el-calendar-table__row--hide-border": string;
  readonly "el-calendar-day": string;
};
export = styles;

