declare const styles: {
  readonly "el-color-predefine": string;
  readonly "el-color-predefine__colors": string;
  readonly "el-color-predefine__color-selector": string;
  readonly "selected": string;
  readonly "is-alpha": string;
  readonly "el-color-hue-slider": string;
  readonly "el-color-hue-slider__bar": string;
  readonly "el-color-hue-slider__thumb": string;
  readonly "is-vertical": string;
  readonly "el-color-svpanel": string;
  readonly "el-color-svpanel__black": string;
  readonly "el-color-svpanel__white": string;
  readonly "el-color-svpanel__cursor": string;
  readonly "el-color-alpha-slider": string;
  readonly "el-color-alpha-slider__bar": string;
  readonly "el-color-alpha-slider__thumb": string;
  readonly "el-color-dropdown": string;
  readonly "el-color-dropdown__main-wrapper": string;
  readonly "el-color-dropdown__btns": string;
  readonly "el-color-dropdown__value": string;
  readonly "el-color-dropdown__btn": string;
  readonly "el-color-dropdown__link-btn": string;
  readonly "el-color-picker": string;
  readonly "is-disabled": string;
  readonly "el-color-picker__trigger": string;
  readonly "el-color-picker--medium": string;
  readonly "el-color-picker__mask": string;
  readonly "el-color-picker--small": string;
  readonly "el-color-picker__empty": string;
  readonly "el-color-picker__icon": string;
  readonly "el-color-picker--mini": string;
  readonly "el-color-picker__color": string;
  readonly "el-color-picker__color-inner": string;
  readonly "el-color-picker__panel": string;
};
export = styles;

