declare const styles: {
  readonly "el-button-group": string;
  readonly "el-button": string;
  readonly "is-active": string;
  readonly "is-disabled": string;
  readonly "is-plain": string;
  readonly "el-button--text": string;
  readonly "is-loading": string;
  readonly "is-round": string;
  readonly "is-circle": string;
  readonly "el-button--primary": string;
  readonly "el-button--success": string;
  readonly "el-button--warning": string;
  readonly "el-button--danger": string;
  readonly "el-button--info": string;
  readonly "el-button--medium": string;
  readonly "el-button--mini": string;
  readonly "el-button--small": string;
  readonly "el-dropdown": string;
  readonly "el-popper": string;
  readonly "popper__arrow": string;
  readonly "el-dropdown__caret-button": string;
  readonly "el-button--default": string;
  readonly "el-dropdown__icon": string;
  readonly "el-dropdown-selfdefine": string;
  readonly "focusing": string;
  readonly "el-dropdown-menu": string;
  readonly "el-dropdown-menu__item": string;
  readonly "el-dropdown-menu__item--divided": string;
  readonly "el-dropdown-menu--medium": string;
  readonly "el-dropdown-menu--small": string;
  readonly "el-dropdown-menu--mini": string;
};
export = styles;

