declare const styles: {
  readonly "el-textarea": string;
  readonly "el-textarea__inner": string;
  readonly "el-input__count": string;
  readonly "is-disabled": string;
  readonly "is-exceed": string;
  readonly "el-input": string;
  readonly "el-input__clear": string;
  readonly "el-input__count-inner": string;
  readonly "el-input__inner": string;
  readonly "el-input__prefix": string;
  readonly "el-input__suffix": string;
  readonly "is-active": string;
  readonly "el-input__suffix-inner": string;
  readonly "el-input__icon": string;
  readonly "el-input__validateIcon": string;
  readonly "el-input--suffix": string;
  readonly "el-input--prefix": string;
  readonly "el-input--medium": string;
  readonly "el-input--small": string;
  readonly "el-input--mini": string;
  readonly "el-input-group": string;
  readonly "el-input-group__append": string;
  readonly "el-input-group__prepend": string;
  readonly "el-input-group--prepend": string;
  readonly "el-input-group--append": string;
  readonly "el-button": string;
  readonly "el-select": string;
  readonly "is-focus": string;
};
export = styles;

