declare const styles: {
  readonly "el-tabs__header": string;
  readonly "el-tabs__active-bar": string;
  readonly "el-tabs__new-tab": string;
  readonly "el-icon-plus": string;
  readonly "el-tabs__nav-wrap": string;
  readonly "el-tabs--border-card": string;
  readonly "el-tabs--card": string;
  readonly "is-scrollable": string;
  readonly "el-tabs__nav-scroll": string;
  readonly "el-tabs__nav-next": string;
  readonly "el-tabs__nav-prev": string;
  readonly "el-tabs__nav": string;
  readonly "is-stretch": string;
  readonly "el-tabs__item": string;
  readonly "is-active": string;
  readonly "is-focus": string;
  readonly "el-icon-close": string;
  readonly "is-disabled": string;
  readonly "el-tabs__content": string;
  readonly "is-closable": string;
  readonly "el-tabs--bottom": string;
  readonly "is-bottom": string;
  readonly "is-top": string;
  readonly "el-tabs--top": string;
  readonly "el-tabs--left": string;
  readonly "el-tabs--right": string;
  readonly "is-left": string;
  readonly "is-right": string;
  readonly "slideInLeft-transition": string;
  readonly "slideInRight-transition": string;
  readonly "slideInRight-enter": string;
  readonly "slideInRight-leave": string;
  readonly "slideInLeft-enter": string;
  readonly "slideInLeft-leave": string;
};
export = styles;

