# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def tx_im
   pod 'TXIMSDK_iOS'
end

def swift_pods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'Toast-Swift'
  pod 'Material'
  pod 'NVActivityIndicatorView'
end

def common_pods_all
  pod 'Bugly' # 检测bug使用，非必须依赖
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'CWStatusBarNotification', '~> 2.3.5'
end

def common_pods_smart
  pod 'CWStatusBarNotification', '~> 2.3.5'
end

def player_pods(subName)
  pod 'SuperPlayer', :path => './TXLiteAVDemo/SuperPlayerKit/SuperPlayer.podspec', :subspecs => ["#{subName}"]
end

target 'TXLiteAVDemo_Enterprise' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for TXLiteAVDemo_Enterprise
  common_pods_all
  player_pods 'Enterprise'
  tx_im
  swift_pods
end

target 'TXLiteAVDemo_Professional' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for TXLiteAVDemo_Professional
  common_pods_all
  swift_pods
  player_pods 'Professional'
  tx_im
end

target 'TXLiteAVDemo_Smart' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for TXLiteAVDemo_Smart
  common_pods_all
  common_pods_smart
  player_pods 'Smart'
  tx_im
  swift_pods
end

target 'TXLiteAVDemo_UGC' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for TXLiteAVDemo_UGC
  common_pods_all
  player_pods 'UGC'
end

target 'TXLiteAVDemo_Player' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for TXLiteAVDemo_Player
  common_pods_all
  player_pods 'Player'
end

target 'TXReplaykitUpload_Enterprise' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for TXReplaykitUpload_Enterprise

end

target 'TXReplaykitUpload_Professional' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for TXReplaykitUpload_Professional

end

target 'TXReplaykitUpload_Smart' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for TXReplaykitUpload_Smart
end

target 'TXLiteAVDemo_TRTC' do
  common_pods_all
  tx_im
  swift_pods
  # TRTC版SDK
  pod 'TXLiteAVSDK_TRTC', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_TRTC.podspec'
end
