# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def common_pods
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'TXIMSDK_iOS'
  pod 'Material'
  pod 'NVActivityIndicatorView'
  pod 'Toast-Swift'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'CWStatusBarNotification', '~> 2.3.5'
end

target 'TRTCScenesDemo' do
  common_pods
end
